name: 'Prepare Test Data'
description: 'Prepare test data for integration tests'
runs:
  using: "composite"
  steps:
    - run: |
        echo "Preparing test data..."
        mkdir -p ${{ github.workspace }}/.github/scripts
      shell: bash