name: "Update check run"
description: "Update check run"
inputs:
    check-run-id:
        description: "ID of Check Run"
        required: true
    status:
        description: "New Status of Check Run"
        required: true
        default: "completed"
    conclusion:
        description: "Conclusion of Check Run"
        required: true
        default: "success"

runs:
    using: "composite"
    steps:
        - uses: actions/github-script@v7
          id: update-run-check
          with:
              github-token: ${{ github.token }}
              script: |
                  const owner = context.repo.owner;
                  const repo = context.repo.repo;
                  const check_run_id = "${{inputs.check-run-id}}";
                  const status = "${{inputs.status}}";
                  const conclusion = "${{inputs.conclusion}}";

                  console.log('Updating check run with:', {
                      owner,
                      repo,
                      check_run_id,
                      status,
                      conclusion
                  });

                  try {
                      await github.rest.checks.update({
                          owner,
                          repo,
                          check_run_id: parseInt(check_run_id),
                          status,
                          conclusion,
                      });
                  } catch (error) {
                      console.error('Error updating check run:', error);
                      throw error;
                  }
