name: 'Create Check Run'
description: 'Create a new check run'
inputs:
  name:
    description: 'Name of the check run'
    required: true
  status:
    description: 'Status of the check run'
    required: false
    default: 'in_progress'
runs:
  using: "composite"
  steps:
    - id: create-check-run
      uses: actions/github-script@v7
      with:
        script: |
          const name = "${{ inputs.name }}";
          const status = "${{ inputs.status }}";
          const repo_data = context.payload.repository.full_name.split("/");
          const commit_sha = context.sha;
          const owner = repo_data[0];
          const repo = repo_data[1];
          const check_url = `${context.serverUrl}/${context.payload.repository.full_name}/actions/runs/${context.runId}`;
          
          const response = await github.rest.checks.create({
              owner,
              repo,
              head_sha: commit_sha,
              name,
              status,
              output: {
                  title: name,
                  summary: "",
                  text: "",
              },
              details_url: check_url,
          });
          
          return response.data.id;
        github-token: ${{ github.token }}