name: Test Integration

on:
  workflow_dispatch:

env:
  # Các biến môi trường cố định cho test
  SERVER_HOST: 192.168.98.123
  SERVER_USER: ubuntu
  SERVER_SSH_PORT: 22
  SERVER_DEPLOY_PATH: /opt/odoo
  SERVER_ODOO_URL: http://192.168.98.123:8069
  SERVER_ODOO_DB_NAME: odoo
  SERVER_DB_PASSWORD: odoo
  ODOO_IMAGE_TAG: 13

  # Các biến cần thiết cho workflows
  LOCAL_BACKUP_FILE_PATH: ${{github.workspace}}/odoo.zip
  SERVER_TEMPORARY_BACKUP_PATH: /tmp/odoo/backup/bep/main
  SERVER_LATEST_BACKUP_FILE_PATH: /tmp/odoo/backup/bep/main/*.zip
  SERVER_CICD_SCRIPT_FOLDER: /tmp/odoo/cicd/bep/main
  CICD_SCRIPTS_PATH: ${{github.workspace}}/.github/scripts
  CICD_UTILS_SCRIPTS_PATH: ${{github.workspace}}/.github/scripts/utils.sh
  ODOO_CONFIG_FILE: ${{github.workspace}}/.github/odoo/etc/odoo.conf

jobs:
  prepare-backup:
    name: Prepare backup
    runs-on: self-hosted
    outputs:
      server_latest_backup_file_path: ${{ steps.update-server-backup-path.outputs.server_latest_backup_file_path }}
      check_run_id: ${{ steps.create-check-run.outputs.check-run-id }}
      use_self_hosted: ${{ steps.get_size.outputs.use_self_hosted }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ env.SERVER_SSH_PORT }} ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts


      - name: Test Preparation
        uses: ./.github/actions/prepare-test-data

      - name: Make decision to create a new backup on server
        run: |
          echo "NEED_NEW_SERVER_BACKUP_FILE=1" >> $GITHUB_ENV

      - name: Upload backup script file to server
        uses: ./.github/actions/scp-ssh
        with:
          direction: "upload"
          host: ${{env.SERVER_HOST}}
          port: ${{env.SERVER_SSH_PORT}}
          user: ${{env.SERVER_USER}}
          ssh_key_text: ${{ secrets.SERVER_PRIVATE_KEY }}
          local_file: ${{ env.CICD_SCRIPTS_PATH }}/server-backup.sh
          server_file: ${{ env.SERVER_CICD_SCRIPT_FOLDER }}

      - name: Backup Odoo on server
        uses: ./.github/actions/ssh-script
        id: backup-on-server
        with:
          host: ${{env.SERVER_HOST}}
          port: ${{env.SERVER_SSH_PORT}}
          user: ${{env.SERVER_USER}}
          ssh_key_text: ${{ secrets.SERVER_PRIVATE_KEY }}
          set-output: 1
          script: |
            bash ${{ env.SERVER_CICD_SCRIPT_FOLDER }}/server-backup.sh "${{env.SERVER_DEPLOY_PATH}}" "${{env.SERVER_ODOO_DB_NAME}}" "${{env.SERVER_DB_PASSWORD}}" "${{env.ODOO_IMAGE_TAG}}" 1 "${{env.SERVER_TEMPORARY_BACKUP_PATH}}"

      - name: Update server backup file path variable
        if: ${{ env.NEED_NEW_SERVER_BACKUP_FILE == 1 }}
        run: |
          latest_backup_file_path=${{ steps.backup-on-server.outputs.script-output }}
          if [[ -n "$latest_backup_file_path" ]]; then
            echo "SERVER_LATEST_BACKUP_FILE_PATH=$latest_backup_file_path" >> $GITHUB_ENV
          fi

      - name: Check backup size and set output
        id: get_size
        env:
          SERVER_HOST: ${{ env.SERVER_HOST }}
          SERVER_USER: ${{ env.SERVER_USER }}
          SERVER_SSH_PORT: ${{ env.SERVER_SSH_PORT }}
          BACKUP_PATH: ${{ env.SERVER_LATEST_BACKUP_FILE_PATH }}
        run: |
          # Debug env
          echo "DEBUG: SERVER_HOST='$SERVER_HOST', SERVER_USER='$SERVER_USER', BACKUP_PATH='$BACKUP_PATH'"
          if [[ -z "$SERVER_HOST" || -z "$SERVER_USER" || -z "$BACKUP_PATH" ]]; then
            echo "Error: SERVER_HOST, SERVER_USER hoặc BACKUP_PATH trống"
            exit 1
          fi

          # SSH connectivity
          ssh -o StrictHostKeyChecking=no -p "$SERVER_SSH_PORT" "$SERVER_USER@$SERVER_HOST" "echo SSH_OK" >/dev/null 2>&1 || {
            echo "Error: SSH connection failed"
            exit 1
          }

          # Kiểm tra file tồn tại
          if ! ssh -o StrictHostKeyChecking=no -p "$SERVER_SSH_PORT" "$SERVER_USER@$SERVER_HOST" "[ -f '$BACKUP_PATH' ]"; then
            echo "Error: File không tồn tại trên server: $BACKUP_PATH"
            exit 1
          fi

          # Lấy kích thước
          size=$(ssh -o StrictHostKeyChecking=no -p "$SERVER_SSH_PORT" "$SERVER_USER@$SERVER_HOST" "stat -c %s '$BACKUP_PATH'" 2>/dev/null || echo "")
          echo "DEBUG: size='$size'"
          if ! [[ "$size" =~ ^[0-9]+$ ]]; then
            echo "Error: Không lấy được size hoặc invalid: '$size'"
            exit 1
          fi

          # So sánh threshold 10 GiB
          threshold=$((10 * 1024 * 1024 * 1024))
          if (( size > threshold )); then
            echo "use_self_hosted=true" >> "$GITHUB_OUTPUT"
          else
            echo "use_self_hosted=false" >> "$GITHUB_OUTPUT"
          fi
  

  integration-test:
    name: Integration test
    needs: prepare-backup
#    runs-on: ${{ needs.prepare-backup.outputs.use_self_hosted == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    runs-on: self-hosted
    permissions:
      checks: write
      contents: read
    env:
      SERVER_LATEST_BACKUP_FILE_PATH: ${{ needs.prepare-backup.outputs.server_latest_backup_file_path }}
    steps:
      - uses: actions/checkout@v4

      - name: Debug scp parameters
        run: |
          echo "DEBUG: SERVER_HOST='${{ env.SERVER_HOST }}'"
          echo "DEBUG: SERVER_SSH_PORT='${{ env.SERVER_SSH_PORT }}'"
          echo "DEBUG: SERVER_USER='${{ env.SERVER_USER }}'"
          echo "DEBUG: LOCAL_BACKUP_FILE_PATH='${{ env.LOCAL_BACKUP_FILE_PATH }}'"
          echo "DEBUG: SERVER_LATEST_BACKUP_FILE_PATH='${{ env.SERVER_LATEST_BACKUP_FILE_PATH }}'"

      - name: Download backup file
        uses: ./.github/actions/scp-ssh
        with:
          direction: "download"
          host: ${{env.SERVER_HOST}}
          port: ${{env.SERVER_SSH_PORT}}
          user: ${{env.SERVER_USER}}
          ssh_key_text: ${{ secrets.SERVER_PRIVATE_KEY }}
          local_file: ${{ env.LOCAL_BACKUP_FILE_PATH }}
          server_file: /tmp/odoo/backup/bep/main/odoo_2025-06-19_03-45-27.zip
          include_file_name: "yes"

      - name: Run Integration test
        id: run_integration_test
        run: |
          bash ${{env.CICD_SCRIPTS_PATH}}/run-integration-test.sh "${{env.LOCAL_BACKUP_FILE_PATH}}" "test_commit" "false"
